spring:

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2
      settings.web-allow-others: true


  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

deezer:
  url: ${url}
  header-host: ${header-host}
  header-key: ${header-key}
  host: ${host}
  key: ${key}
