server:
  port: 8081
spring:
  datasource:
    url: jdbc:sqlite:guessthesong.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1

  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      show_sql: false
      ddl-auto: update
    properties:
      hibernate.id.new_generator_mappings: false

deezer:
  url: https://api.deezer.com/
  url-playlist: https://api.deezer.com/playlist/
