spring:

  datasource:
    url: jdbc:mariadb://bancoguessthesong.cooevgnmvfwz.sa-east-1.rds.amazonaws.com/bancoguessthesong
    username: admin
    password: admin1234
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
       show_sql: false
       ddl-auto: update
#        format_sql: true


#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings.web-allow-others: true

deezer:
  url: ${url}
  url-playlist: ${url-playlist}
  header-host: ${header-host}
  header-key: ${header-key}
  host: ${host}
  key: ${key}
