name: Verificação de Branches

on:
  schedule:
    - cron: "* * * * *"
  push:
    branches:
      - master
      - feat-englishVersion

jobs:
  branch-comparison:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Comparar datas das branches
      run: |
        git fetch --all --prune
        git checkout feat-englishVersion
        develop_date=$(git log -1 --format="%ct")
        git checkout master
        master_date=$(git log -1 --format="%ct")
        date_diff=$(( (master_date - develop_date) / 86400 ))
        if [[ $date_diff -gt 7 ]]; then
          echo "A branch feat-englishVersion está $date_diff dias à frente da branch main. Por favor, sincronize suas alterações."

          # Criar uma issue
          echo "::set-output name=issue-title::Aviso de Sincronização de Branches"
          echo "::set-output name=issue-body::A branch feat-englishVersion está $date_diff dias à frente da branch main. Por favor, sincronize suas alterações."
        fi

    - name: Criar issue
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueTitle = `${{ steps.branch-comparison.outputs.issue-title }}`.trim();
          const issueBody = `${{ steps.branch-comparison.outputs.issue-body }}`.trim();
          const assignees = `${{ github.event.head_commit.author.username }}`;

          const issue = await github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: issueTitle,
            body: issueBody,
            assignees: [assignees]
          });

          console.log('Issue created:', issue.data.html_url);


