name: Verificação de Branches

on:
  schedule:
    - cron: "* * * * *"
  push:
    branches:
      - master
      - feat-englishVersion

jobs:
  branch-comparison:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Comparar datas das branches
      run: |
        git fetch --all --prune
        git checkout feat-englishVersion
        develop_date=$(git log -1 --format="%ct")
        git checkout master
        master_date=$(git log -1 --format="%ct")
        date_diff=$(( (master_date - develop_date) / 86400 ))
        if [[ $date_diff -gt 7 ]]; then
          echo "A branch feat-englishVersion está $date_diff dias à frente da branch main. Por favor, sincronize suas alterações."

          # Criar uma issue
          echo "::set-output name=issue-title::Aviso de Sincronização de Branches"
          echo "::set-output name=issue-body::A branch feat-englishVersion está $date_diff dias à frente da branch main. Por favor, sincronize suas alterações."
        fi
        
    - name: Obter informações do último commit
      id: commit-info
      run: |
        last_commit=$(git log -1 --pretty=format:"%h - %an: %s")
        echo "::set-output name=commit-details::${last_commit}"

    - name: Criar issue
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Último Commit
        body: |
          Informações do commit:

          Autor: ${{ steps.commit-info.outputs.commit-details }}










