name: Verificação de Branches

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
      - develop

jobs:
  branch-comparison:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Comparar datas das branches
      run: |
        git fetch --all --prune
        git checkout feat-englishVersion
        develop_date=$(git log -1 --format="%ct")
        git checkout main
        master_date=$(git log -1 --format="%ct")
        date_diff=$(( (master_date - develop_date) / 86400 ))
        if [[ $date_diff -gt 7 ]]; then
          echo "A branch develop está $date_diff dias à frente da branch master. Por favor, sincronize suas alterações."

          # Criar uma issue
          echo "::set-output name=issue-title::Aviso de Sincronização de Branches"
          echo "::set-output name=issue-body::A branch develop está $date_diff dias à frente da branch master. Por favor, sincronize suas alterações."
        fi
        
    - name: Criar issue
      id: create-issue
      uses: peter-evans/create-issue@v2
      with:
        title: ${{ steps.branch-comparison.outputs.issue-title }}
        body: ${{ steps.branch-comparison.outputs.issue-body }}
        assignees: ${{ github.event.head_commit.author.username }}

