name: Verificação de Branches

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  branch-comparison:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Listar branches
        run: git fetch --all --prune

      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Obter informações do último commit da branch feat-englishVersion
        id: commit-info
        run: |
          git fetch --all --prune
          git checkout feat-englishVersion
          commit_author=$(git log -1 --format="%an")
          commit_id=$(git log -1 --format="%H")
          commit_message=$(git log -1 --format="%s")
          commit_date=$(git log -1 --format="%cd")
          echo "::set-output name=commit-author::$commit_author"
          echo "::set-output name=commit-id::$commit_id"
          echo "::set-output name=commit-message::$commit_message"
          echo "::set-output name=commit-date::$commit_date"


      - name: Comparar datas das branches
        id: branch-comparison
        run: |
          git fetch --all --prune
          git checkout master
          master_date=$(git log -1 --format="%ct")
          git checkout feat-englishVersion
          develop_date=$(git log -1 --format="%ct")
          date_diff=$(( (master_date - develop_date) / 86400 ))
          echo "::set-output name=date-diff::$date_diff"

      - name: Criar issue se a diferença for maior que 30 dias
        if: ${{ steps.branch-comparison.outputs.date-diff > 30 }}
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const title = 'Aviso de Sincronização de Branches';
            const body = `
              A branch feat-englishVersion está ${{ steps.branch-comparison.outputs.date-diff }} dias à frente da branch main. Por favor, sincronize suas alterações.

              **Informações do commit:**
              - Autor: ${{ steps.commit-info.outputs.commit-author }}
              - ID do commit: ${{ steps.commit-info.outputs.commit-id }}
              - Mensagem do commit: ${{ steps.commit-info.outputs.commit-message }}
              - Data do commit: ${{ steps.commit-info.outputs.commit-date }}
            `;
            const assignees = ['${{ steps.commit-info.outputs.commit-author }}'];
            const labels = [
                {
                  name: 'Alerta',
                  color: 'FF0000' // Cor vermelha em hexadecimal
                },
                {
                  name: 'Mergear',
                  color: '00FF00' // Cor verde em hexadecimal
                }
              ];
            
            const { data } = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              assignees,
              labels: labels
            });
            console.log(`Issue criada com sucesso: ${data.html_url}`);
