AWSTemplateFormatVersion: "2010-09-09"
Description: "Template description"

Parameters:
  AppEnvironment:
    Type: String
    Default: production
  EC2InstanceType: 
    Type: String
    Default: a1.medium
  AccountVpc:
    Type: AWS::EC2::VPC::Id
    Description: Account VPC
    Default: vpc-id
  EC2Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet subnet-1
    Default: subnet-1-id
  LoadBalancerSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet subnet-1
    Default: subnet-1-id
  LoadBalancerVisibility:
    Type: String
    Default: public

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket

  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: my-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-function
      Runtime: python3.8
      Handler: index.lambda_handler
      Code:
        S3Bucket: my-bucket
        S3Key: function.zip
      MemorySize: 256
      Timeout: 30

  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-queue
