name: List AWS Resources

on:
  push:
    branches:
      - master

jobs:
  list-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List AWS Resources
        id: get_resources
        run: |
          # Extrair os recursos do arquivo template.yml
          resources=$(grep "Resources:" template.yml -A 9999 | awk '/^  [A-Za-z0-9]/ {print $1}')
          echo "::set-output name=resources::$resources"

      - name: Create Issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = 'AWS Resources in template.yml';
            const resources = '${{ steps.get_resources.outputs.resources }}';
            const body = `
              The following AWS resources are defined in the CloudFormation template:
            
              ${resources}
            `;

            const { data } = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body
            });
            console.log(`Issue created successfully: ${data.html_url}`);
