name: List AWS Resources

on:
  push:
    branches:
      - master

jobs:
  list-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Execute list-resources.js
        run: node list-resources.js

      - name: Create Issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = 'AWS Resources in template.yml';
            const resources = JSON.parse('${{ steps.get_resources.outputs.resources }}');
            const body = `
              The following AWS resources are defined in the CloudFormation template:
            
              ${resources.join('\n')}
            `;

            const { data } = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body
            });
            console.log(`Issue created successfully: ${data.html_url}`);
