name: List AWS Resources and Create Issue

on:
  push:
    branches:
      - master

jobs:
  list-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install yaml
        run: npm install yaml

      - name: Execute list-resources.js
        run: npm list-resorces.js
             
      - name: Create Issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const resources = fs.readFileSync('resources.txt', 'utf8').trim().split('\n');
            const body = `
              The following AWS resources are defined in the CloudFormation template:
            
              ${resources.join('\n')}
            `;

            const { data } = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'AWS Resources in template.yml',
              body: body
            });
            console.log(`Issue created successfully: ${data.html_url}`);
