name: Listar Issues de Repositórios Específicos

on:
  workflow_dispatch:

jobs:
  list-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Listar issues
        id: list-issues
        run: |
          TOKEN=$GITHUB_TOKEN
          REPOSITORIES="GaberRB/guess-the-song GaberRB/tengu"

          for REPO in $REPOSITORIES; do
            ISSUES=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO/issues?state=all" | jq -r ".[].title")
            echo "Repositório: $REPO"
            echo "Issues:"
            while IFS= read -r ISSUE; do
              echo "$ISSUE"
            done <<< "$ISSUES"
            echo "---"
          done
