name: List GitHub Issues

on:
  workflow_dispatch:
  
jobs:
  list-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install jq

      - name: List issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPOSITORIES="GaberRB/guess-the-song GaberRB/tengu"
          for REPO in $REPOSITORIES; do
            RESPONSE=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/$REPO/issues")
            ISSUES=$(echo "$RESPONSE" | jq -r ".[].title")
            echo "Repositório: $REPO"
            echo "Issues:"
            while IFS= read -r ISSUE; do
              echo "$ISSUE"
            done <<< "$ISSUES"
            echo "---"
